version: '2'
services:

  nginx:
    extends:
      file: common-services.yml
      service: nginx-base
    volumes_from:
      - gunicorn
    depends_on:
      - gunicorn

  gunicorn:
    extends:
      file: common-services.yml
      service: gunicorn-base
    depends_on:
      - redis
      - postgres
      - rabbitmq
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: '{{ cookiecutter.project_slug }}.settings.production'

  redis:
    extends:
      file: common-services.yml
      service: redis-base

  postgres:
    extends:
      file: common-services.yml
      service: postgres-base
    env_file:
      - .env

  rabbitmq:
    extends:
      file: common-services.yml
      service: rabbitmq-base

  flower:
    extends:
      service: gunicorn
    entrypoint:
      - celery
      - flower
      - --app={{cookiecutter.project_slug}}

  celeryworker:
    extends:
      service: gunicorn
    entrypoint:
      - celery
      - -A
      - {{cookiecutter.project_slug}}
      - worker
      - -l
      - INFO

  celerybeat:
    extends:
      service: gunicorn
    entrypoint:
      - celery
      - -A
      - {{cookiecutter.project_slug}}
      - beat
      - -l
      - INFO
